version: 0.1

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn -X package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/quote-services-0.1.0.jar
  discard-paths: yes
