branch-defaults:
  master:
    environment: Quoteservice-env2
    group_suffix: mygrp
deploy:
  artifact: target/quote-services-0.1.0.jar
global:
  application_name: quote-service
  default_ec2_keyname: id_rsa_aws
  profile: eb-cli
  sc: git
  workspace_type: Application
